package tools.colors;

@javax.annotation.Generated(value = {"dashboard.Main"}, date = "Tuesday, June 21, 2016 10:45:55 AM UTC")
public final class NamedColorConstants
{
	private NamedColorConstants(){}
	
	/**A color with an ARGB value of 0xFFF0F8FF<div style="border:1px solid black;width:40px;height:20px;background-color:#F0F8FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int AliceBlue = 0xFFF0F8FF;
	/**A color with an ARGB value of 0xFFFAEBD7<div style="border:1px solid black;width:40px;height:20px;background-color:#FAEBD7;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int AntiqueWhite = 0xFFFAEBD7;
	/**A color with an ARGB value of 0xFF00FFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#00FFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Aqua = 0xFF00FFFF;
	/**A color with an ARGB value of 0xFF7FFFD4<div style="border:1px solid black;width:40px;height:20px;background-color:#7FFFD4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Aquamarine = 0xFF7FFFD4;
	/**A color with an ARGB value of 0xFFF0FFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#F0FFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Azure = 0xFFF0FFFF;
	/**A color with an ARGB value of 0xFFF5F5DC<div style="border:1px solid black;width:40px;height:20px;background-color:#F5F5DC;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Beige = 0xFFF5F5DC;
	/**A color with an ARGB value of 0xFFFFE4C4<div style="border:1px solid black;width:40px;height:20px;background-color:#FFE4C4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Bisque = 0xFFFFE4C4;
	/**A color with an ARGB value of 0xFF000000<div style="border:1px solid black;width:40px;height:20px;background-color:#000000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Black = 0xFF000000;
	/**A color with an ARGB value of 0xFFFFEBCD<div style="border:1px solid black;width:40px;height:20px;background-color:#FFEBCD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int BlanchedAlmond = 0xFFFFEBCD;
	/**A color with an ARGB value of 0xFF0000FF<div style="border:1px solid black;width:40px;height:20px;background-color:#0000FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Blue = 0xFF0000FF;
	/**A color with an ARGB value of 0xFF8A2BE2<div style="border:1px solid black;width:40px;height:20px;background-color:#8A2BE2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int BlueViolet = 0xFF8A2BE2;
	/**A color with an ARGB value of 0xFFA52A2A<div style="border:1px solid black;width:40px;height:20px;background-color:#A52A2A;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Brown = 0xFFA52A2A;
	/**A color with an ARGB value of 0xFFDEB887<div style="border:1px solid black;width:40px;height:20px;background-color:#DEB887;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int BurlyWood = 0xFFDEB887;
	/**A color with an ARGB value of 0xFF5F9EA0<div style="border:1px solid black;width:40px;height:20px;background-color:#5F9EA0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int CadetBlue = 0xFF5F9EA0;
	/**A color with an ARGB value of 0xFF7FFF00<div style="border:1px solid black;width:40px;height:20px;background-color:#7FFF00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Chartreuse = 0xFF7FFF00;
	/**A color with an ARGB value of 0xFFD2691E<div style="border:1px solid black;width:40px;height:20px;background-color:#D2691E;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Chocolate = 0xFFD2691E;
	/**A color with an ARGB value of 0xFFFF7F50<div style="border:1px solid black;width:40px;height:20px;background-color:#FF7F50;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Coral = 0xFFFF7F50;
	/**A color with an ARGB value of 0xFF6495ED<div style="border:1px solid black;width:40px;height:20px;background-color:#6495ED;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int CornflowerBlue = 0xFF6495ED;
	/**A color with an ARGB value of 0xFFFFF8DC<div style="border:1px solid black;width:40px;height:20px;background-color:#FFF8DC;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Cornsilk = 0xFFFFF8DC;
	/**A color with an ARGB value of 0xFFDC143C<div style="border:1px solid black;width:40px;height:20px;background-color:#DC143C;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Crimson = 0xFFDC143C;
	/**A color with an ARGB value of 0xFF00FFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#00FFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Cyan = 0xFF00FFFF;
	/**A color with an ARGB value of 0xFF00008B<div style="border:1px solid black;width:40px;height:20px;background-color:#00008B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkBlue = 0xFF00008B;
	/**A color with an ARGB value of 0xFF008B8B<div style="border:1px solid black;width:40px;height:20px;background-color:#008B8B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkCyan = 0xFF008B8B;
	/**A color with an ARGB value of 0xFFB8860B<div style="border:1px solid black;width:40px;height:20px;background-color:#B8860B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkGoldenRod = 0xFFB8860B;
	/**A color with an ARGB value of 0xFFA9A9A9<div style="border:1px solid black;width:40px;height:20px;background-color:#A9A9A9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkGray = 0xFFA9A9A9;
	/**A color with an ARGB value of 0xFFA9A9A9<div style="border:1px solid black;width:40px;height:20px;background-color:#A9A9A9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkGrey = 0xFFA9A9A9;
	/**A color with an ARGB value of 0xFF006400<div style="border:1px solid black;width:40px;height:20px;background-color:#006400;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkGreen = 0xFF006400;
	/**A color with an ARGB value of 0xFFBDB76B<div style="border:1px solid black;width:40px;height:20px;background-color:#BDB76B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkKhaki = 0xFFBDB76B;
	/**A color with an ARGB value of 0xFF8B008B<div style="border:1px solid black;width:40px;height:20px;background-color:#8B008B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkMagenta = 0xFF8B008B;
	/**A color with an ARGB value of 0xFF556B2F<div style="border:1px solid black;width:40px;height:20px;background-color:#556B2F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkOliveGreen = 0xFF556B2F;
	/**A color with an ARGB value of 0xFFFF8C00<div style="border:1px solid black;width:40px;height:20px;background-color:#FF8C00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkOrange = 0xFFFF8C00;
	/**A color with an ARGB value of 0xFF9932CC<div style="border:1px solid black;width:40px;height:20px;background-color:#9932CC;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkOrchid = 0xFF9932CC;
	/**A color with an ARGB value of 0xFF8B0000<div style="border:1px solid black;width:40px;height:20px;background-color:#8B0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkRed = 0xFF8B0000;
	/**A color with an ARGB value of 0xFFE9967A<div style="border:1px solid black;width:40px;height:20px;background-color:#E9967A;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkSalmon = 0xFFE9967A;
	/**A color with an ARGB value of 0xFF8FBC8F<div style="border:1px solid black;width:40px;height:20px;background-color:#8FBC8F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkSeaGreen = 0xFF8FBC8F;
	/**A color with an ARGB value of 0xFF483D8B<div style="border:1px solid black;width:40px;height:20px;background-color:#483D8B;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkSlateBlue = 0xFF483D8B;
	/**A color with an ARGB value of 0xFF2F4F4F<div style="border:1px solid black;width:40px;height:20px;background-color:#2F4F4F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkSlateGray = 0xFF2F4F4F;
	/**A color with an ARGB value of 0xFF2F4F4F<div style="border:1px solid black;width:40px;height:20px;background-color:#2F4F4F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkSlateGrey = 0xFF2F4F4F;
	/**A color with an ARGB value of 0xFF00CED1<div style="border:1px solid black;width:40px;height:20px;background-color:#00CED1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkTurquoise = 0xFF00CED1;
	/**A color with an ARGB value of 0xFF9400D3<div style="border:1px solid black;width:40px;height:20px;background-color:#9400D3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DarkViolet = 0xFF9400D3;
	/**A color with an ARGB value of 0xFFFF1493<div style="border:1px solid black;width:40px;height:20px;background-color:#FF1493;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DeepPink = 0xFFFF1493;
	/**A color with an ARGB value of 0xFF00BFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#00BFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DeepSkyBlue = 0xFF00BFFF;
	/**A color with an ARGB value of 0xFF696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DimGray = 0xFF696969;
	/**A color with an ARGB value of 0xFF696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DimGrey = 0xFF696969;
	/**A color with an ARGB value of 0xFF1E90FF<div style="border:1px solid black;width:40px;height:20px;background-color:#1E90FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int DodgerBlue = 0xFF1E90FF;
	/**A color with an ARGB value of 0xFFB22222<div style="border:1px solid black;width:40px;height:20px;background-color:#B22222;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int FireBrick = 0xFFB22222;
	/**A color with an ARGB value of 0xFFFFFAF0<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFAF0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int FloralWhite = 0xFFFFFAF0;
	/**A color with an ARGB value of 0xFF228B22<div style="border:1px solid black;width:40px;height:20px;background-color:#228B22;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int ForestGreen = 0xFF228B22;
	/**A color with an ARGB value of 0xFFFF00FF<div style="border:1px solid black;width:40px;height:20px;background-color:#FF00FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Fuchsia = 0xFFFF00FF;
	/**A color with an ARGB value of 0xFFDCDCDC<div style="border:1px solid black;width:40px;height:20px;background-color:#DCDCDC;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Gainsboro = 0xFFDCDCDC;
	/**A color with an ARGB value of 0xFFF8F8FF<div style="border:1px solid black;width:40px;height:20px;background-color:#F8F8FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int GhostWhite = 0xFFF8F8FF;
	/**A color with an ARGB value of 0xFFFFD700<div style="border:1px solid black;width:40px;height:20px;background-color:#FFD700;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Gold = 0xFFFFD700;
	/**A color with an ARGB value of 0xFFDAA520<div style="border:1px solid black;width:40px;height:20px;background-color:#DAA520;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int GoldenRod = 0xFFDAA520;
	/**A color with an ARGB value of 0xFF808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Gray = 0xFF808080;
	/**A color with an ARGB value of 0xFF808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Grey = 0xFF808080;
	/**A color with an ARGB value of 0xFF008000<div style="border:1px solid black;width:40px;height:20px;background-color:#008000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Green = 0xFF008000;
	/**A color with an ARGB value of 0xFFADFF2F<div style="border:1px solid black;width:40px;height:20px;background-color:#ADFF2F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int GreenYellow = 0xFFADFF2F;
	/**A color with an ARGB value of 0xFFF0FFF0<div style="border:1px solid black;width:40px;height:20px;background-color:#F0FFF0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int HoneyDew = 0xFFF0FFF0;
	/**A color with an ARGB value of 0xFFFF69B4<div style="border:1px solid black;width:40px;height:20px;background-color:#FF69B4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int HotPink = 0xFFFF69B4;
	/**A color with an ARGB value of 0xFFCD5C5C<div style="border:1px solid black;width:40px;height:20px;background-color:#CD5C5C;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int IndianRed = 0xFFCD5C5C;
	/**A color with an ARGB value of 0xFF4B0082<div style="border:1px solid black;width:40px;height:20px;background-color:#4B0082;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Indigo = 0xFF4B0082;
	/**A color with an ARGB value of 0xFFFFFFF0<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFFF0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Ivory = 0xFFFFFFF0;
	/**A color with an ARGB value of 0xFFF0E68C<div style="border:1px solid black;width:40px;height:20px;background-color:#F0E68C;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Khaki = 0xFFF0E68C;
	/**A color with an ARGB value of 0xFFE6E6FA<div style="border:1px solid black;width:40px;height:20px;background-color:#E6E6FA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Lavender = 0xFFE6E6FA;
	/**A color with an ARGB value of 0xFFFFF0F5<div style="border:1px solid black;width:40px;height:20px;background-color:#FFF0F5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LavenderBlush = 0xFFFFF0F5;
	/**A color with an ARGB value of 0xFF7CFC00<div style="border:1px solid black;width:40px;height:20px;background-color:#7CFC00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LawnGreen = 0xFF7CFC00;
	/**A color with an ARGB value of 0xFFFFFACD<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFACD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LemonChiffon = 0xFFFFFACD;
	/**A color with an ARGB value of 0xFFADD8E6<div style="border:1px solid black;width:40px;height:20px;background-color:#ADD8E6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightBlue = 0xFFADD8E6;
	/**A color with an ARGB value of 0xFFF08080<div style="border:1px solid black;width:40px;height:20px;background-color:#F08080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightCoral = 0xFFF08080;
	/**A color with an ARGB value of 0xFFE0FFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#E0FFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightCyan = 0xFFE0FFFF;
	/**A color with an ARGB value of 0xFFFAFAD2<div style="border:1px solid black;width:40px;height:20px;background-color:#FAFAD2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightGoldenRodYellow = 0xFFFAFAD2;
	/**A color with an ARGB value of 0xFFD3D3D3<div style="border:1px solid black;width:40px;height:20px;background-color:#D3D3D3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightGray = 0xFFD3D3D3;
	/**A color with an ARGB value of 0xFFD3D3D3<div style="border:1px solid black;width:40px;height:20px;background-color:#D3D3D3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightGrey = 0xFFD3D3D3;
	/**A color with an ARGB value of 0xFF90EE90<div style="border:1px solid black;width:40px;height:20px;background-color:#90EE90;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightGreen = 0xFF90EE90;
	/**A color with an ARGB value of 0xFFFFB6C1<div style="border:1px solid black;width:40px;height:20px;background-color:#FFB6C1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightPink = 0xFFFFB6C1;
	/**A color with an ARGB value of 0xFFFFA07A<div style="border:1px solid black;width:40px;height:20px;background-color:#FFA07A;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSalmon = 0xFFFFA07A;
	/**A color with an ARGB value of 0xFF20B2AA<div style="border:1px solid black;width:40px;height:20px;background-color:#20B2AA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSeaGreen = 0xFF20B2AA;
	/**A color with an ARGB value of 0xFF87CEFA<div style="border:1px solid black;width:40px;height:20px;background-color:#87CEFA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSkyBlue = 0xFF87CEFA;
	/**A color with an ARGB value of 0xFF778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSlateGray = 0xFF778899;
	/**A color with an ARGB value of 0xFF778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSlateGrey = 0xFF778899;
	/**A color with an ARGB value of 0xFFB0C4DE<div style="border:1px solid black;width:40px;height:20px;background-color:#B0C4DE;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightSteelBlue = 0xFFB0C4DE;
	/**A color with an ARGB value of 0xFFFFFFE0<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFFE0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LightYellow = 0xFFFFFFE0;
	/**A color with an ARGB value of 0xFF00FF00<div style="border:1px solid black;width:40px;height:20px;background-color:#00FF00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Lime = 0xFF00FF00;
	/**A color with an ARGB value of 0xFF32CD32<div style="border:1px solid black;width:40px;height:20px;background-color:#32CD32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int LimeGreen = 0xFF32CD32;
	/**A color with an ARGB value of 0xFFFAF0E6<div style="border:1px solid black;width:40px;height:20px;background-color:#FAF0E6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Linen = 0xFFFAF0E6;
	/**A color with an ARGB value of 0xFFFF00FF<div style="border:1px solid black;width:40px;height:20px;background-color:#FF00FF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Magenta = 0xFFFF00FF;
	/**A color with an ARGB value of 0xFF800000<div style="border:1px solid black;width:40px;height:20px;background-color:#800000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Maroon = 0xFF800000;
	/**A color with an ARGB value of 0xFF66CDAA<div style="border:1px solid black;width:40px;height:20px;background-color:#66CDAA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumAquaMarine = 0xFF66CDAA;
	/**A color with an ARGB value of 0xFF0000CD<div style="border:1px solid black;width:40px;height:20px;background-color:#0000CD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumBlue = 0xFF0000CD;
	/**A color with an ARGB value of 0xFFBA55D3<div style="border:1px solid black;width:40px;height:20px;background-color:#BA55D3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumOrchid = 0xFFBA55D3;
	/**A color with an ARGB value of 0xFF9370DB<div style="border:1px solid black;width:40px;height:20px;background-color:#9370DB;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumPurple = 0xFF9370DB;
	/**A color with an ARGB value of 0xFF3CB371<div style="border:1px solid black;width:40px;height:20px;background-color:#3CB371;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumSeaGreen = 0xFF3CB371;
	/**A color with an ARGB value of 0xFF7B68EE<div style="border:1px solid black;width:40px;height:20px;background-color:#7B68EE;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumSlateBlue = 0xFF7B68EE;
	/**A color with an ARGB value of 0xFF00FA9A<div style="border:1px solid black;width:40px;height:20px;background-color:#00FA9A;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumSpringGreen = 0xFF00FA9A;
	/**A color with an ARGB value of 0xFF48D1CC<div style="border:1px solid black;width:40px;height:20px;background-color:#48D1CC;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumTurquoise = 0xFF48D1CC;
	/**A color with an ARGB value of 0xFFC71585<div style="border:1px solid black;width:40px;height:20px;background-color:#C71585;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MediumVioletRed = 0xFFC71585;
	/**A color with an ARGB value of 0xFF191970<div style="border:1px solid black;width:40px;height:20px;background-color:#191970;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MidnightBlue = 0xFF191970;
	/**A color with an ARGB value of 0xFFF5FFFA<div style="border:1px solid black;width:40px;height:20px;background-color:#F5FFFA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MintCream = 0xFFF5FFFA;
	/**A color with an ARGB value of 0xFFFFE4E1<div style="border:1px solid black;width:40px;height:20px;background-color:#FFE4E1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int MistyRose = 0xFFFFE4E1;
	/**A color with an ARGB value of 0xFFFFE4B5<div style="border:1px solid black;width:40px;height:20px;background-color:#FFE4B5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Moccasin = 0xFFFFE4B5;
	/**A color with an ARGB value of 0xFFFFDEAD<div style="border:1px solid black;width:40px;height:20px;background-color:#FFDEAD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int NavajoWhite = 0xFFFFDEAD;
	/**A color with an ARGB value of 0xFF000080<div style="border:1px solid black;width:40px;height:20px;background-color:#000080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Navy = 0xFF000080;
	/**A color with an ARGB value of 0xFFFDF5E6<div style="border:1px solid black;width:40px;height:20px;background-color:#FDF5E6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int OldLace = 0xFFFDF5E6;
	/**A color with an ARGB value of 0xFF808000<div style="border:1px solid black;width:40px;height:20px;background-color:#808000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Olive = 0xFF808000;
	/**A color with an ARGB value of 0xFF6B8E23<div style="border:1px solid black;width:40px;height:20px;background-color:#6B8E23;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int OliveDrab = 0xFF6B8E23;
	/**A color with an ARGB value of 0xFFFFA500<div style="border:1px solid black;width:40px;height:20px;background-color:#FFA500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Orange = 0xFFFFA500;
	/**A color with an ARGB value of 0xFFFF4500<div style="border:1px solid black;width:40px;height:20px;background-color:#FF4500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int OrangeRed = 0xFFFF4500;
	/**A color with an ARGB value of 0xFFDA70D6<div style="border:1px solid black;width:40px;height:20px;background-color:#DA70D6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Orchid = 0xFFDA70D6;
	/**A color with an ARGB value of 0xFFEEE8AA<div style="border:1px solid black;width:40px;height:20px;background-color:#EEE8AA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PaleGoldenRod = 0xFFEEE8AA;
	/**A color with an ARGB value of 0xFF98FB98<div style="border:1px solid black;width:40px;height:20px;background-color:#98FB98;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PaleGreen = 0xFF98FB98;
	/**A color with an ARGB value of 0xFFAFEEEE<div style="border:1px solid black;width:40px;height:20px;background-color:#AFEEEE;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PaleTurquoise = 0xFFAFEEEE;
	/**A color with an ARGB value of 0xFFDB7093<div style="border:1px solid black;width:40px;height:20px;background-color:#DB7093;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PaleVioletRed = 0xFFDB7093;
	/**A color with an ARGB value of 0xFFFFEFD5<div style="border:1px solid black;width:40px;height:20px;background-color:#FFEFD5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PapayaWhip = 0xFFFFEFD5;
	/**A color with an ARGB value of 0xFFFFDAB9<div style="border:1px solid black;width:40px;height:20px;background-color:#FFDAB9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PeachPuff = 0xFFFFDAB9;
	/**A color with an ARGB value of 0xFFCD853F<div style="border:1px solid black;width:40px;height:20px;background-color:#CD853F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Peru = 0xFFCD853F;
	/**A color with an ARGB value of 0xFFFFC0CB<div style="border:1px solid black;width:40px;height:20px;background-color:#FFC0CB;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Pink = 0xFFFFC0CB;
	/**A color with an ARGB value of 0xFFDDA0DD<div style="border:1px solid black;width:40px;height:20px;background-color:#DDA0DD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Plum = 0xFFDDA0DD;
	/**A color with an ARGB value of 0xFFB0E0E6<div style="border:1px solid black;width:40px;height:20px;background-color:#B0E0E6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int PowderBlue = 0xFFB0E0E6;
	/**A color with an ARGB value of 0xFF800080<div style="border:1px solid black;width:40px;height:20px;background-color:#800080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Purple = 0xFF800080;
	/**A color with an ARGB value of 0xFF663399<div style="border:1px solid black;width:40px;height:20px;background-color:#663399;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int RebeccaPurple = 0xFF663399;
	/**A color with an ARGB value of 0xFFFF0000<div style="border:1px solid black;width:40px;height:20px;background-color:#FF0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Red = 0xFFFF0000;
	/**A color with an ARGB value of 0xFFBC8F8F<div style="border:1px solid black;width:40px;height:20px;background-color:#BC8F8F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int RosyBrown = 0xFFBC8F8F;
	/**A color with an ARGB value of 0xFF4169E1<div style="border:1px solid black;width:40px;height:20px;background-color:#4169E1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int RoyalBlue = 0xFF4169E1;
	/**A color with an ARGB value of 0xFF8B4513<div style="border:1px solid black;width:40px;height:20px;background-color:#8B4513;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SaddleBrown = 0xFF8B4513;
	/**A color with an ARGB value of 0xFFFA8072<div style="border:1px solid black;width:40px;height:20px;background-color:#FA8072;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Salmon = 0xFFFA8072;
	/**A color with an ARGB value of 0xFFF4A460<div style="border:1px solid black;width:40px;height:20px;background-color:#F4A460;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SandyBrown = 0xFFF4A460;
	/**A color with an ARGB value of 0xFF2E8B57<div style="border:1px solid black;width:40px;height:20px;background-color:#2E8B57;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SeaGreen = 0xFF2E8B57;
	/**A color with an ARGB value of 0xFFFFF5EE<div style="border:1px solid black;width:40px;height:20px;background-color:#FFF5EE;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SeaShell = 0xFFFFF5EE;
	/**A color with an ARGB value of 0xFFA0522D<div style="border:1px solid black;width:40px;height:20px;background-color:#A0522D;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Sienna = 0xFFA0522D;
	/**A color with an ARGB value of 0xFFC0C0C0<div style="border:1px solid black;width:40px;height:20px;background-color:#C0C0C0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Silver = 0xFFC0C0C0;
	/**A color with an ARGB value of 0xFF87CEEB<div style="border:1px solid black;width:40px;height:20px;background-color:#87CEEB;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SkyBlue = 0xFF87CEEB;
	/**A color with an ARGB value of 0xFF6A5ACD<div style="border:1px solid black;width:40px;height:20px;background-color:#6A5ACD;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SlateBlue = 0xFF6A5ACD;
	/**A color with an ARGB value of 0xFF708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SlateGray = 0xFF708090;
	/**A color with an ARGB value of 0xFF708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SlateGrey = 0xFF708090;
	/**A color with an ARGB value of 0xFFFFFAFA<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFAFA;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Snow = 0xFFFFFAFA;
	/**A color with an ARGB value of 0xFF00FF7F<div style="border:1px solid black;width:40px;height:20px;background-color:#00FF7F;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SpringGreen = 0xFF00FF7F;
	/**A color with an ARGB value of 0xFF4682B4<div style="border:1px solid black;width:40px;height:20px;background-color:#4682B4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int SteelBlue = 0xFF4682B4;
	/**A color with an ARGB value of 0xFFD2B48C<div style="border:1px solid black;width:40px;height:20px;background-color:#D2B48C;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Tan = 0xFFD2B48C;
	/**A color with an ARGB value of 0xFF008080<div style="border:1px solid black;width:40px;height:20px;background-color:#008080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Teal = 0xFF008080;
	/**A color with an ARGB value of 0xFFD8BFD8<div style="border:1px solid black;width:40px;height:20px;background-color:#D8BFD8;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Thistle = 0xFFD8BFD8;
	/**A color with an ARGB value of 0xFFFF6347<div style="border:1px solid black;width:40px;height:20px;background-color:#FF6347;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Tomato = 0xFFFF6347;
	/**A color with an ARGB value of 0x00000000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(0,0,0,0.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Transparent = 0x00000000;
	/**A color with an ARGB value of 0xFF40E0D0<div style="border:1px solid black;width:40px;height:20px;background-color:#40E0D0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Turquoise = 0xFF40E0D0;
	/**A color with an ARGB value of 0xFFEE82EE<div style="border:1px solid black;width:40px;height:20px;background-color:#EE82EE;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Violet = 0xFFEE82EE;
	/**A color with an ARGB value of 0xFFF5DEB3<div style="border:1px solid black;width:40px;height:20px;background-color:#F5DEB3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Wheat = 0xFFF5DEB3;
	/**A color with an ARGB value of 0xFFFFFFFF<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFFFF;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int White = 0xFFFFFFFF;
	/**A color with an ARGB value of 0xFFF5F5F5<div style="border:1px solid black;width:40px;height:20px;background-color:#F5F5F5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int WhiteSmoke = 0xFFF5F5F5;
	/**A color with an ARGB value of 0xFFFFFF00<div style="border:1px solid black;width:40px;height:20px;background-color:#FFFF00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int Yellow = 0xFFFFFF00;
	/**A color with an ARGB value of 0xFF9ACD32<div style="border:1px solid black;width:40px;height:20px;background-color:#9ACD32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public static final int YellowGreen = 0xFF9ACD32;
	
}
